server:
    listen 8080
    host localhost
    server_name webserv.net
    client_max_body_size 10m
    location:
        root www/webserv.net
        index index.html
    error_page:
        400 ./www/post42.net/html/400.html
        403 ./www/post42.net/html/403.html
        404 ./www/post42.net/html/404.html
        500 ./www/post42.net/html/500.html

server:
    listen 4040
    host localhost
    server_name post42.net
    client_max_body_size 20m
    location:
        root www/post42.net
        index index.html
    error_page:
        400 ./www/post42.net/html/400.html
        403 ./www/post42.net/html/403.html
        404 ./www/post42.net/html/403.html
        500 ./www/post42.net/html/500.html
