server:
    listen 8080
    host localhost
    server_name webserv.net
    client_max_body_size 10m
    location:
        root www/webserv.net
        index index.html

server:
    listen 4040
    host localhost
    server_name post42.net
    client_max_body_size 20m
    location:
        root www/post42.net
        index index.html
