# You can take inspiration from the ’server’ section of the NGINX
# configuration file.
# In the configuration file, you should be able to:
http {
    server {
        # •Choose the port and host of each ’server’.
        # •The first server for a host:port will be the default for this
        # host:port (meaning it will respond to all requests that do not belong
        # to another server).
        listen 80 default_server;

        # •Set up the server_names or not.
        server_name webserv.com www.webserv.com

        # •Set the maximum allowed size for client request bodies.
        client_max_body_size 0m;
    }
    # •Set up default error pages.
    error_page  404  /404.html;
}
# •Set up routes with one or multiple of the following rules/configurations
# (routes won’t be using regexp):
# ◦Define a list of accepted HTTP methods for the route.
# ◦Define an HTTP redirect.
# ◦Define a directory or file where the requested file should be located (e.g.,
# if url /kapouet is rooted to /tmp/www, url /kapouet/pouic/toto/pouet is
# /tmp/www/pouic/toto/pouet).
# ◦Enable or disable directory listing.
# ◦Set a default file to serve when the request is for a directory.
# ◦Execute CGI based on certain file extension (for example .php).
# ◦Make it work with POST and GET methods.
# ◦Allow the route to accept uploaded files and configure where they should be
# saved.
# ∗Do you wonder what a CGI is?
# ∗Because you won’t call the CGI directly, use the full path as PATH_INFO.
# ∗Just remember that, for chunked requests, your server needs to unchunk
# them, the CGI will expect EOF as the end of the body.
# ∗The same applies to the output of the CGI. If no content_length is
# returned from the CGI, EOF will mark the end of the returned data.
# ∗Your program should call the CGI with the file requested as the first
# argument.
# ∗The CGI should be run in the correct directory for relative path file access.
# ∗Your server should support at least one CGI (php-CGI, Python, and so
# forth).
# You must provide configuration files and default files to test and demonstrate that
# every feature works during the evaluation.
# If you have a question about a specific behavior, you should compare
# your program’s behavior with NGINX’s.
# For example, check how the server_name works.
# We have provided a small tester. Using it is not mandatory if
# everything works fine with your browser and tests, but it can help
# you find and fix bugs.
# Resilience is key. Your server must remain operational at all times.
# Do not test with only one program. Write your tests in a more
# suitable language, such as Python or Golang, among others, even
# in C or C++ if you prefer.
