http {
    server {
        server_name webserv.com www.webserv.com
        listen localhost:8080
    }
    server {
        listen localhost:8181
    }
}


; server {
;     listen 8080;
;     root website;

;     location / {
;         root website/html;
;         index index.html;
;     }

;     location /threads/ {
;         root website;
;         allow_methods GET;
;         autoindex on;
;     }

;     location /images/ {
;         root website;
;         allow_methods GET;
;     }

;     location /assets/ {
;         root website;
;         allow_methods GET;
;     }

;     location /style.css {
;         root website/html;
;         allow_methods GET;
;     }
; }
