server:
    listen 8080
    host localhost
    server_name webserv.com
    client_max_body_size 10m
    error_page:
        400 /400.html
        401 /401.html
        402 /402.html
        403 /403.html
        404 /404.html
        500 /500.html
        500x /50x.html
    redirection:
        301 /new-page
    location /kapouet:
            root /tmp/www
            index index.html
    cgi:
        .php /usr/bin/php-cgi
        .pl /usr/bin/perl
        .py /usr/bin/python3