server:
    listen 8080
    server_name webserv.com
    client_max_body_size 10m
    location:
        root /tmp/www
        index index.html
    error_page:
        40x /www/webserv.com/40x.html
        50x /www/webserv.com/50x.html
    redirection:
        301 /new-page
    cgi:
        .php /usr/bin/php-cgi
        .pl /usr/bin/perl
        .py /usr/bin/python3
